### ISSUE TITLE
UnicodeDecodeError with foxconda

### ISSUE THREAD

**Issue by BaptisteDugue** [foxBMS/tools#1]
Hello,
I'm installing foxconda following the foxBMS documentation and I cannot run fbterminal properly. After the installation in the default directory c:\foxconda, when I run fbterminal.exe before uploading the git source of foxbms (from the command ghloader -u https://github.com/foxBMS/foxBMS-setup.git --script bootstrap.py), I reveived the following message from the command windows :
I can't fix the problem... I tried to install the same way on another computer and it worked well. What is goint wrong with this new computer ?

Traceback (most recent call last):
  File "C:\foxconda\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\foxconda\lib\site-packages\conda\cli\main.py", line 178, in main
    init_loggers()
  File "C:\foxconda\lib\site-packages\conda\cli\main.py", line 84, in init_loggers
    from ..console import setup_verbose_handlers
  File "C:\foxconda\lib\site-packages\conda\console.py", line 9, in <module>
    from .base.context import context
  File "C:\foxconda\lib\site-packages\conda\base\context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\foxconda\lib\site-packages\conda\common\configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "C:\foxconda\lib\site-packages\conda\common\configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\foxconda\lib\site-packages\conda\common\configuration.py", line 364, in load_file_configs
    expanded_paths = tuple(expand(path) for path in search_path)
  File "C:\foxconda\lib\site-packages\conda\common\configuration.py", line 364, in <genexpr>
    expanded_paths = tuple(expand(path) for path in search_path)
  File "C:\foxconda\lib\site-packages\conda\common\path.py", line 247, in expand
    return abspath(expanduser(expandvars(path)))
  File "C:\foxconda\lib\ntpath.py", line 311, in expanduser
    return userhome + path[i:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 21: ordinal not in range(128)

C:\foxconda\Scripts>

I already try to insert the 2 following lines in the fbterminal-script (taken from a conda forum) :
reload(sys)  
sys.setdefaultencoding('utf8')

After adding these 2 lines, the command windows open brievly and then close. I cannot enter the ghloader -u https://github.com/foxBMS/foxBMS-setup.git --script bootstrap.py command.

Thanks for helping,
Best regards,
Baptiste

**Comment by BaptisteDugue** [comment]
Apparently the problem comes from my user name defined in Windows (C:\user\myname). There is an accent in "myname". I had to create a new user profil without accent and it worked. But I now I have 2 windows account... One for foxconda, a second for daily use.
